### ISSUE TITLE
Inverted issue in Domoticz

### ISSUE THREAD

**Issue by ab10002** [MadPatrick/somfy#13]
Regarding this issue https://github.com/domoticz/domoticz/issues/5288
I'v done some mods:
```
#        if (str(Command) == "Off"):
#            commands["name"] = "close"
#        elif (str(Command) == "On"):
#            commands["name"] = "open"
        if (str(Command) == "Off"):
            commands["name"] = "open"
        elif (str(Command) == "On"):
            commands["name"] = "close"
        elif (str(Command) == "Stop"):
            commands["name"] = "stop"
        elif ("Set Level" in str(Command)):
            commands["name"] = "setClosure"
#            tmp = 100 - int(Level)
            tmp = int(Level)
            params.append(tmp)
            commands["parameters"] = params

                  if ((state["name"] == "core:ClosureState") or (state["name"] == "core:DeploymentState")):
                    level = int(state["value"])
                    # Delete# level = 100 - level
                    status_l = True

```

**Comment by MadPatrick** [comment]
Thanks for the post.
I've quickly tested the mod, but then you must change the Switch type from "Blinds Inverted" to "Blinds"
Also the Blinds Percentage does not work.

**Comment by ab10002** [comment]
> Thanks for the post. I've quickly tested the mod, but then you must change the Switch type from "Blinds Inverted" to "Blinds" Also the Blinds Percentage does not work.

That was the coal.. odd the blind/percentage device doesn't work for you.
I'm using now blind/percentage+stop 
![image](https://user-images.githubusercontent.com/80668868/187422183-e2acaefe-886f-4644-8fba-9e1bcadbca91.png)

**Comment by ab10002** [comment]
No, maybe somewhere a fault line?

**Comment by MadPatrick** [comment]
I doubt. It is a complete different call and i used copy/paste
Which version are you using ?
Master or AddNewRollerShutter

**Comment by ab10002** [comment]
Master.

Sometimes i'v got a somfy API error, due to many connections. That's set very low by Somfy

**Comment by MadPatrick** [comment]
I've created a new Branch "Beta" 
Please check if this is working

**Comment by ab10002** [comment]
> I've created a new Branch "Beta" Please check if this is working

Tested. Works perfect👍

**Comment by MadPatrick** [comment]
Ok. The only thing now is to make the Switch type different when created

**Comment by ab10002** [comment]
I'v a Sunis (Somfy lux sensor) i see it in the log. Is there a way to build in?

**Comment by MadPatrick** [comment]
> > Ok. The only thing now is to make the Switch type different when created
> 
> +stop😎

Changed "Stop" to "My"

please check

**Comment by ab10002** [comment]
> > > Ok. The only thing now is to make the Switch type different when created
> > 
> > 
> > +stop😎
> 
> Changed "Stop" to "My"
> 
> please check

Pse no, i'v test that.. And then stop does'nt work. So i'v changed that back to stop.
And for MY, you can send levels ##

**Comment by MadPatrick** [comment]
My bad..... i though the command in the script needed a change.
Corrected it back

Also Switch type is change to Normal.
Can you check if you make/add a new device if the switch type is now good.

**Comment by ab10002** [comment]
> Also Switch type is change to Normal. Can you check if you make/add a new device if the switch type is now good.
Mm, what do you mean?

**Comment by MadPatrick** [comment]
if you install the plugin and no devices are yet in Domoticz it will create the Somfy devices
Since you maybe already have the devices added to Domoticz it will skip this
When you remove a device and restart the plugin it will add the device again
Only now as different switch type

**Comment by ab10002** [comment]
The wrong device is created
![image](https://user-images.githubusercontent.com/80668868/187482026-93629762-065a-4d6c-afcf-6c7b501fd599.png)

Must be blind+stop
![image](https://user-images.githubusercontent.com/80668868/187482366-dda2f6cc-264c-4006-b299-042217a09370.png)

**Comment by MadPatrick** [comment]
I noticed it also ;-)
Now changed, but device will be "Blinds Percentage"

**Comment by ab10002** [comment]
No, should be blinds+stop. that is with percentage

**Comment by MadPatrick** [comment]
> No, should be blinds+stop. that is with percentage

This devices is not working with Dashticz.
The percentage will disappear and will become a On?off button

**Comment by ab10002** [comment]
New subtype for blind+stop (with percentage) is 21
https://www.domoticz.com/wiki/Domoticz_API/JSON_URL%27s
