### ISSUE TITLE
No more MQTT output from domoticz

### ISSUE THREAD

**Issue by MikeyMan83** [MadPatrick/somfy#38]
Hi!

It seems there is no more MQTT output with the latest version of the plugin.
Don't know if there's something i can check to help out?

**Comment by JanJaapKo** [comment]
This is not an issue with the plugin but 'something' in Domoticz, as far as I'm concerned. You can see what is going on on the MQTT output by:
`mosquitto_sub -h localhost -t 'domoticz/out'` perhaps you can find some clues there.
