### ISSUE TITLE
Errors after startup plugin

### ISSUE THREAD

**Issue by ab10002** [MadPatrick/somfy#41]
[domoticz.log](https://github.com/MadPatrick/somfy/files/10365923/domoticz.log)

[somfy.log](https://github.com/MadPatrick/somfy/files/10365924/somfy.log)

**Comment by ab10002** [comment]
Probably caused by domoticz, after an update there were no more errors.

**Comment by ab10002** [comment]
Unfortunately, the same errors again today. Still not sure how or what caused it. Suspect it comes after a series of commands through a script.

**Comment by ab10002** [comment]
My shutters continued to commute this morning. Only a reboot helped. I'v rolled back to v4.1.17

**Comment by JanJaapKo** [comment]
Ok, please provide clear error description and full logging, otherwise it is a bit a needle in a haystack....

**Comment by MadPatrick** [comment]
I've update to the latest version 4.2.11 because i was still on 4.1.7 on my production server
I can not reproduce these errors

**Comment by JanJaapKo** [comment]
unclear issue.
