### ISSUE TITLE
Support of ELIXO 500 3S IO

### ISSUE THREAD

**Issue by Chaussette23** [MadPatrick/somfy#51]
It's more a question than an issue.

Hello,

I have a Connexoon in local mode and it works perfectly fine with all my roller shutters. I have all three "modules" with my connexoon.

I plan to buy a portal motor ELIXO 500 3S IO. The idea is to be able to drive it also with Domoticz and with this plugin.

Is it supported yet ? Do you know if it would be possible to get its state (open/closed, or even the opening percentage would be awsome).

Thanks !

**Comment by MadPatrick** [comment]
Hi Chaussette23,

I'm not sure if it is supported.
My thoughts are if it connect with the Connexoon it could be working

You need to read out the devices and see if it is reconized.
Then we can add it to the plugin

**Comment by Chaussette23** [comment]
Ok, I think I will go for it and let you know !

I close the the ticket for now and I will keep you updated.
