### ISSUE TITLE
Error 404 in get ...refreshAllStates  since Cozytouch app new version 3.6.3#411 

### ISSUE THREAD

**Issue by Aldou63** [MadPatrick/somfy#52]
Since 24th may It's not possible to run python Somfy Cozytouch.
I have this error:
Démarrage Cozytouch Aeromax5  2023-05-31 16:16
GET->   https://ha110-1.overkiz.com/enduser-mobile-web/externalAPI/json/refreshAllStates   :   404
Erreur Cozytouch_GET http: 404     2023-05-31 16:16
!!!! Echec interrogation serveur Cozytouch sans login, connexion serveur Cozytouch ****
 POST-> https://ha110-1.overkiz.com/enduser-mobile-web/enduserAPI/login | userId=****&userPassword=**** : 200
Authentification serveur cozytouch OK
Connexion serveur Cozytouch reussie
GET->   https://ha110-1.overkiz.com/enduser-mobile-web/externalAPI/json/refreshAllStates   :   404
Erreur Cozytouch_GET http: 404     2023-05-31 16:16
Echec requete refreshAllStates  2023-05-31 16:16

I have a connexoon box and the new android cozytouch 3.6.3 is OK. Everything was working well when the previous version of Cozytouch was in use

**Comment by Tatroxitum** [comment]
Same here since may 24th
According to somfy website also app doesn't work anymore :
https://www.somfy.fr/ralentissements-des-serveurs/ralentissements-des-serveurs-box-domotiques
Seems like overkiz is down : https://ha110-1.overkiz.com/pro-flex-backend/pro-html5-client/index.html
I hope they'll find a solution soon

**Comment by MadPatrick** [comment]
Since it is a problem on the Somfy side it is difficult to solve this
Try otherwise the local mode, since this is undependent from the Somfy website and still works (with my devices)

**Comment by JanJaapKo** [comment]
Server sided issue, can't be solved here

**Comment by Aldou63** [comment]
I made an error in the destination of issue . I have two  box one somfy and another cozytouch. On the somfy box there was also a problem but i have changed the old plugin web  version to the new and it works well in local mode. For the connexoon box the issue was for [OBone-git]
/
[Cozytouch-domoticz].
Sorry !
