### ISSUE TITLE
External awning don't update in local mode.

### ISSUE THREAD

**Issue by Aldou63** [MadPatrick/somfy#53]
Hi,
I have 5 roller shutters, 1 luminance sensor, 1 external awning (somfy io) and a connexoon bridge. I was using plugin from nonolk/domoticz v1.0.5 with some modification to use luminance sensor and awning. It works very well for many years . Some weeks ago the web plugin stop working so I switch to the new plugin V 4.2.16 with local requests. it work very well with luminance sensor and roller shutters but awning don't update level of deployement.
An update is only done when I use manually awning slider and just after one roller slider ??? Set level or remote somfy never update deployement level.
I use domoticz 2022.1-python version 3.7.3 but I made also a test with 2023.1  and  it's the same problem . I try to debug the problem but today I have not any result.

**Comment by Aldou63** [comment]
Just find the problem:  add "core:DeploymentState" in stateSet  in utils.py.

line 5
 stateSet = {"core:ClosureState","core:OpenClosedState","core:LuminanceState"} #list of states that trigger domoticz widget update
----------------->
stateSet = {"core:ClosureState","core:OpenClosedState","core:LuminanceState","core:DeploymentState"} #list of states that trigger domoticz widget update

And also in update_device_status in plugin.py don't invert awning open/close percentage
line 394
if ((state["name"] == "core:ClosureState") or (state["name"] == "core:DeploymentState")):
    level = int(state["value"])
    level = 100 - level #invert open/close percentage
    status_num = 1
 
---------------->

if (state["name"] == "core:ClosureState"):
    level = int(state["value"])
    level = 100 - level #invert open/close percentage
    status_num = 1
    
if  (state["name"] == "core:DeploymentState"):
    logging.info("Store update ="+str(state["value"]))
    level = int(state["value"])  #Don't invert awning  open/close percentage
    status_num = 1

**Comment by Aldou63** [comment]
Oups 
Suppress logging.info("Store update ="+str(state["value"])) it was for me to debug !

And also in update_device_status in plugin.py don't invert awning open/close percentage
line 394
if ((state["name"] == "core:ClosureState") or (state["name"] == "core:DeploymentState")):
level = int(state["value"])
level = 100 - level #invert open/close percentage
status_num = 1

---------------->

if (state["name"] == "core:ClosureState"):
level = int(state["value"])
level = 100 - level #invert open/close percentage
status_num = 1

if (state["name"] == "core:DeploymentState"):
level = int(state["value"]) #Don't invert awning open/close percentage
status_num = 1

**Comment by MadPatrick** [comment]
Good job.
I've updated the Beta branch.
Casn you check if it is working correctly

**Comment by Aldou63** [comment]
It works well for my awning but to start the plugin I had to change the new line 151 of the beta version in tahoma_local.py
self.base_url_local = "https://gateway-" + str(pin) + ":" + str(port) + "/enduser-mobile-web/1/enduserAPI"
to ------>
self.base_url_local = "https://gateway-" + str(pin) + ".local:" + str(port) + "/enduser-mobile-web/1/enduserAPI"

And  so it works with no modification of the hosts file (In my network connexoon mDNS Name is gateway-xxxx-xxxx-xxxx.local) ??

**Comment by MadPatrick** [comment]
changed it in beta branch
Was already changed in master branch

Thanks for the support
