### ISSUE TITLE
level issue

### ISSUE THREAD

**Issue by ab10002** [MadPatrick/somfy#6]
Hi,

I'v tested this plugin and having issue's with levels.
Open en closing is oke, sending a level (%) also.
But then.. imho the current position (in %)  in not reading by the plugin..

And see this in the log;
Error: Switch command not send!, Hardware device disabled or not found!

grz

**Comment by MadPatrick** [comment]
> 

What kind of switch did make with your device.
It should be the type: "Blinds Percentage Inverted"

The switchlooks like a dimmer in Domoticz

**Comment by ab10002** [comment]
Yes, i'm using that type.
The Nonolk plug, i don't have this issue..

**Comment by MadPatrick** [comment]
> Yes, i'm using that type. The Nonolk plug, i don't have this issue..

Can you post the somfy.log

DId you try to restart the plugin, since you have an hardware error

**Comment by ab10002** [comment]
Sure

[somfy.log](https://github.com/MadPatrick/somfy/files/8496056/somfy.log)
